language: php

# Outline PHP versions to test against
php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4

before_install:
  - travis_retry composer self-update
  - composer install --no-interaction

script:
  - php vendor/bin/phpunit